# Generated by Django 5.0.3 on 2024-10-18 04:21

import django.db.models.deletion
import mptt.fields
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('wiki', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Report',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('revision_id', models.IntegerField()),
                ('article_id', models.IntegerField()),
                ('revision_num', models.IntegerField()),
                ('report_type', models.CharField(max_length=255)),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('current_page', models.CharField(max_length=255)),
            ],
        ),
        migrations.AddField(
            model_name='article',
            name='has_potential_spoilers',
            field=models.BooleanField(default=False, help_text='If this is checked, the article will be marked as containing potential spoilers. This is a hint to the reader that the article may contain spoilers.', verbose_name='has potential spoilers'),
        ),
        migrations.AddField(
            model_name='urlpath',
            name='moved_to',
            field=mptt.fields.TreeForeignKey(blank=True, help_text='Article path was moved to this location', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='moved_from', to='wiki.urlpath', verbose_name='Moved to'),
        ),
        migrations.AlterField(
            model_name='articleforobject',
            name='content_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='content_type_set_for_%(class)s', to='contenttypes.contenttype', verbose_name='content type'),
        ),
        migrations.AlterField(
            model_name='urlpath',
            name='level',
            field=models.PositiveIntegerField(editable=False),
        ),
        migrations.AlterField(
            model_name='urlpath',
            name='lft',
            field=models.PositiveIntegerField(editable=False),
        ),
        migrations.AlterField(
            model_name='urlpath',
            name='rght',
            field=models.PositiveIntegerField(editable=False),
        ),
        migrations.CreateModel(
            name='Privilege',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('status', models.CharField(choices=[('ACTIVE', 'Active'), ('SUSPENDED', 'Suspended')], default='ACTIVE', max_length=10)),
                ('penalty_start', models.DateField(blank=True, null=True)),
                ('infractions', models.PositiveIntegerField(default=0)),
                ('total_allowed_infractions', models.PositiveIntegerField(default=3)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='privileges', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='InfractionEvent',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('article_title', models.CharField(max_length=200)),
                ('date', models.DateField(auto_now_add=True)),
                ('article_history_link', models.URLField(max_length=500)),
                ('admin_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='administered_infractions', to=settings.AUTH_USER_MODEL)),
                ('privilege', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='infraction_events', to='wiki.privilege')),
            ],
        ),
        migrations.CreateModel(
            name='RecentlyVisitedWikiPages',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.URLField(blank=True, max_length=255, null=True)),
                ('visited_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recently_visited_wiki_pages', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('profile_image', models.ImageField(blank=True, null=True, upload_to='profile_pics/')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='UserProgress',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('wiki_id', models.CharField(max_length=255)),
                ('progress', models.CharField(max_length=255)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='progresses', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
