# Generated by Django 5.0.3 on 2024-10-17 21:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('wiki', '0002_report_urlpath_moved_to_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Report',
        ),
    ]
