# Generated by Django 5.0.3 on 2024-05-28 21:16

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wiki', '0003_mptt_upgrade'),
    ]

    operations = [
        migrations.CreateModel(
            name='ChatHistory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('session_id', models.CharField(max_length=255, verbose_name='session ID')),
                ('user_message', models.TextField(verbose_name='user message')),
                ('bot_response', models.TextField(verbose_name='bot response')),
                ('timestamp', models.DateTimeField(default=django.utils.timezone.now, verbose_name='timestamp')),
                ('article_revision', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='chat_histories', to='wiki.articlerevision', verbose_name='article revision')),
            ],
            options={
                'verbose_name': 'Chat History',
                'verbose_name_plural': 'Chat Histories',
                'ordering': ['-timestamp'],
            },
        ),
    ]
