# Generated by Django 5.0.3 on 2024-11-15 03:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('wiki', '0003_discussionboards'),
    ]

    operations = [
        migrations.DeleteModel(
            name='DiscussionBoard',
        ),
    ]
