# Generated by Django 5.0.3 on 2024-10-17 21:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wiki', '0003_delete_report'),
    ]

    operations = [
        migrations.CreateModel(
            name='Report',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('revision_id', models.IntegerField()),
                ('article_id', models.IntegerField()),
                ('revision_num', models.IntegerField()),
                ('report_type', models.CharField(max_length=255)),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('current_page', models.CharField(max_length=255)),
            ],
        ),
    ]
