# Generated by Django 5.0.3 on 2024-11-05 01:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('wiki', '0004_chathistory'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ChatHistory',
        ),
    ]
