# Generated by Django 5.0.3 on 2024-11-15 05:23

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wiki', '0005_discussionboard_delete_discussionboards'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DiscussionBoards',
            fields=[
                ('article_id', models.IntegerField()),
                ('content', models.TextField(blank=True, verbose_name='discussion_content')),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('post_id', models.AutoField(primary_key=True, serialize=False)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='discussion_boards', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.DeleteModel(
            name='DiscussionBoard',
        ),
    ]
