# Generated by Django 5.0.3 on 2024-09-06 22:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wiki', '0005_userprofile_urls_alter_userprofile_profile_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='urls',
            field=models.JSONField(default=list, null=True),
        ),
    ]
