# Generated by Django 5.0.3 on 2024-09-06 22:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wiki', '0006_alter_userprofile_urls'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='urls',
            field=models.JSONField(default=list),
        ),
    ]
