# Generated by Django 5.0.3 on 2024-09-12 01:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('wiki', '0005_alter_userprofile_profile_image'),
        ('wiki', '0008_alter_userprofile_urls'),
    ]

    operations = [
    ]
