# Generated by Django 5.0.3 on 2024-11-15 19:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wiki', '0008_discussionreport'),
    ]

    operations = [
        migrations.AddField(
            model_name='discussionreport',
            name='current_page',
            field=models.CharField(default='empty', max_length=255),
            preserve_default=False,
        ),
    ]
