# Generated by Django 5.0.3 on 2024-09-12 01:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('wiki', '0008_alter_userprofile_urls'),
        ('wiki', '0008_userprogress'),
    ]

    operations = [
    ]
