# Generated by Django 5.0.3 on 2024-09-12 02:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('wiki', '0009_merge_0008_alter_userprofile_urls_0008_userprogress'),
        ('wiki', '0009_merge_20240911_1945'),
    ]

    operations = [
    ]
