# Generated by Django 5.0.3 on 2024-11-15 20:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('wiki', '0004_userprofile_account_created'),
        ('wiki', '0009_discussionreport_current_page'),
    ]

    operations = [
    ]
