# Generated by Django 5.0.3 on 2024-09-28 01:16

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wiki', '0010_merge_20240911_2001'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Privilege',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('status', models.CharField(choices=[('ACTIVE', 'Active'), ('SUSPENDED', 'Suspended')], default='ACTIVE', max_length=10)),
                ('penalty_length', models.DurationField()),
                ('total_allowed_infractions', models.PositiveIntegerField(default=3)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='USER_PRIVILEGE', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='InfractionEvent',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('article_title', models.CharField(max_length=200)),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('article_history_link', models.URLField(max_length=500)),
                ('admin_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='administered_infractions', to=settings.AUTH_USER_MODEL)),
                ('privilege', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='infraction_events', to='wiki.privilege')),
            ],
        ),
    ]
