# Generated by Django 5.0.3 on 2024-10-17 00:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wiki', '0010_merge_20240911_2001'),
    ]

    operations = [
        migrations.CreateModel(
            name='InfractionEvent',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='Privileges',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='Report',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('revision_num', models.IntegerField()),
                ('report_type', models.CharField(max_length=255)),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('current_page', models.CharField(max_length=255)),
                ('article_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='wiki.article')),
                ('revision_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='wiki.articlerevision')),
            ],
        ),
    ]
