# Generated by Django 5.0.3 on 2024-10-17 00:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('wiki', '0011_infractionevent_privileges_report'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='report',
            name='article_id',
        ),
        migrations.RemoveField(
            model_name='report',
            name='revision_id',
        ),
    ]
