# Generated by Django 5.0.3 on 2024-09-28 02:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wiki', '0012_alter_privilege_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='privilege',
            name='infractions',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
