# Generated by Django 5.0.3 on 2024-09-28 03:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wiki', '0013_privilege_infractions'),
    ]

    operations = [
        migrations.AddField(
            model_name='privilege',
            name='penalty_start',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
