# Generated by Django 5.0.3 on 2024-09-30 06:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wiki', '0014_privilege_penalty_start'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='privilege',
            name='penalty_length',
        ),
        migrations.AddField(
            model_name='privilege',
            name='penalty_end',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
