# Generated by Django 5.0.3 on 2024-09-30 06:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wiki', '0015_remove_privilege_penalty_length_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='privilege',
            name='penalty_length',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
