# Generated by Django 5.0.3 on 2024-09-30 06:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wiki', '0016_privilege_penalty_length'),
    ]

    operations = [
        migrations.AlterField(
            model_name='privilege',
            name='penalty_length',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
