# Generated by Django 5.0.3 on 2024-10-15 04:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wiki', '0018_remove_privilege_penalty_length_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='has_potential_spoilers',
            field=models.BooleanField(default=False, help_text='If this is checked, the article will be marked as containing potential spoilers. This is a hint to the reader that the article may contain spoilers.', verbose_name='has potential spoilers'),
        ),
    ]
