# Generated by Django 5.0.3 on 2024-10-16 01:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wiki', '0019_article_has_potential_spoilers'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='privilege',
            name='penalty_end',
        ),
        migrations.AlterField(
            model_name='infractionevent',
            name='date',
            field=models.DateField(auto_now_add=True),
        ),
    ]
