# Generated by Django 5.0.3 on 2024-10-16 04:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wiki', '0021_remove_userprofile_urls_recentlyvisited'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='urls',
            field=models.JSONField(blank=True, default=list, null=True),
        ),
        migrations.DeleteModel(
            name='RecentlyVisited',
        ),
    ]
