# THANKS!
# https://travis-ci.org/peterbe/premailer

# This indicates to Travis that we will not use or need sudo
# so that we can benefit from and use the cache->directories
# directive.

sudo: false

env: PIP_DOWNLOAD_CACHE="pip_cache"

language: python

addons:
  apt:
    sources:
      - deadsnakes
    packages:
      - python3.5
      - python3-dev
      - libjpeg9
      - libjpeg9-dev

# See tox.ini for env list
env:
- TOXENV=py27-django18
- TOXENV=py27-django19
- TOXENV=py27-django110
- TOXENV=py34-django18
- TOXENV=py34-django19
- TOXENV=py34-django110
- TOXENV=py35-django18
- TOXENV=py35-django19
- TOXENV=py35-django110

install:
  - pip install tox>=2.1 coveralls

script:
  - tox -e $TOXENV

notifications:
  irc:
    - "irc.freenode.org#django-wiki"

after_success:
  - coverage combine
  - coveralls
