# Because Python 3.6 is available on GCE
sudo: required
dist: trusty

env: PIP_DOWNLOAD_CACHE="pip_cache"

language: python

python: 3.6

addons:
  apt:
    packages:
      - libjpeg8
      - libjpeg8-dev

# See tox.ini for env list
env:
- TOXENV=py27-django18
- TOXENV=py27-django19
- TOXENV=py27-django110
- TOXENV=py27-django111
- TOXENV=py34-django18
- TOXENV=py34-django19
- TOXENV=py34-django110
- TOXENV=py34-django111
- TOXENV=py35-django18
- TOXENV=py35-django19
- TOXENV=py35-django110
- TOXENV=py35-django111
- TOXENV=py36-django111
- TOXENV=lint

install:
  - pip install tox>=2.1

script:
  - tox -e $TOXENV

notifications:
  irc:
    - "irc.freenode.org#django-wiki"

after_success:
  - bash <(curl -s https://codecov.io/bash)
