# Because Python 3.6 is available on GCE
sudo: required
dist: trusty

env: PIP_DOWNLOAD_CACHE="pip_cache"

language: python

python:
  - "2.7"
  - "3.4"
  - "3.5"
  - "3.6"

addons:
  apt:
    packages:
      - libjpeg8
      - libjpeg8-dev

install:
  - pip install tox>=2.1 tox-travis

script:
  - tox

notifications:
  irc:
    - "irc.freenode.org#django-wiki"

after_success:
  - bash <(curl -s https://codecov.io/bash)
